var merge = require('webpack-merge');

var commonData = require('./commonData');

module.exports = {
  //自然人基本信息
"hitTimeChart": merge(commonData, {
  "data": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            5,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            5,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
        ]
      }),
//淘宝账号信息表
list: merge(commonData, {
    "data": [
            {
                "identityType": 1,
                "idCard": "2102041977" ,
                "accountId": "12345678",
                "riskLevel": 3,
                "judgedTime": null,
                "photo": null,
                "hitTime": "2015-12-07 10:59:10",
                "hitNum": 1,
                "featureRuleType": {
                    "low": 1,
                    "judgedFlg": false,
                    "medium": 0,
                    "high": 3
                },
                "hitNmaes": "入住频次异常",
                "judgedFlg": 1,
                "registerType": null,
                "actionRuleType": {
                    "low": 1,
                    "judgedFlg": false,
                    "medium": 0,
                    "high": 1
                },
                "taobaoName": "淘宝名字",
                "name": "阿凡提",
                "relationRuleType": {
                    "low": 2,
                    "judgedFlg": false,
                    "medium": 2,
                    "high": 0
                },
                "accountType": 2,
                "alipayName": null,
                "locusRuleType": {
                    "low": 4,
                    "judgedFlg": false,
                    "medium": 0,
                    "high": 1
                }
            },
            {
                "identityType": 2,
                "idCard": "2102041985",
                "accountId": "2102041985",
                "riskLevel": 3,
                "judgedTime": null,
                "photo": null,
                "hitTime": "2015-12-07 10:57:21",
                "hitNum": 2,
                "featureRuleType": {
                    "low": 3,
                    "judgedFlg": false,
                    "medium": 0,
                    "high": 1
                },
                "hitNames": "购买锻造工具,购买体能提升物品",
                "judgedFlg": 2,
                "registerType": 3,
                "actionRuleType": {
                    "low": 0,
                    "judgedFlg": false,
                    "medium": 0,
                    "high": 0
                },
                "taobaoName": null,
                "name": "刘某某",
                "relationRuleType": {
                    "low": 3,
                    "judgedFlg": false,
                    "medium": 0,
                    "high": 2
                },
                "accountType": 1,
                "alipayName": null,
                "locusRuleType": {
                    "low": 0,
                    "judgedFlg": false,
                    "medium": 0,
                    "high": 0
                }
            },
            {
                "identityType": 3,
                "idCard": "2102041966",
                "accountId": "987654",
                "riskLevel": 3,
                "judgedTime": null,
                "photo": null,
                "hitTime": "2015-12-07 10:59:55",
                "hitNum": 2,
                "featureRuleType": {
                    "low": 0,
                    "judgedFlg": false,
                    "medium": 1,
                    "high": 0
                },
                "hitNmaes": "上网频次异常,大额转账至多人",
                "judgedFlg": 1,
                "registerType": null,
                "actionRuleType": {
                    "low": 0,
                    "judgedFlg": false,
                    "medium": 0,
                    "high": 0
                },
                "taobaoName": null,
                "name": "丁彦某某",
                "relationRuleType": {
                    "low": 0,
                    "judgedFlg": false,
                    "medium": 0,
                    "high": 4
                },
                "accountType": 2,
                "alipayName": "支付宝名字",
                "locusRuleType": {
                    "low": 0,
                    "judgedFlg": false,
                    "medium": 0,
                    "high": 3
                }
            },
            {
                "identityType": 1,
                "idCard": "2102041999",
                "accountId": "2102041999",
                "riskLevel": 2,
                "judgedTime": "2015-12-05 14:36:57",
                "photo": null,
                "hitTime": "2015-12-07 09:42:32",
                "hitNum": 3,
                "featureRuleType": {
                    "low": 1,
                    "judgedFlg": false,
                    "medium": 0,
                    "high": 0
                },
                "hitNmaes": "不准出境报备人员,持护照,与重点人员多次同出入境",
                "judgedFlg": 0,
                "registerType": 1,
                "actionRuleType": {
                    "low": 2,
                    "judgedFlg": false,
                    "medium": 0,
                    "high": 0
                },
                "taobaoName": null,
                "name": "张某某",
                "relationRuleType": {
                    "low": 0,
                    "judgedFlg": false,
                    "medium": 0,
                    "high":1
                },
                "accountType": 1,
                "alipayName": null,
                "locusRuleType": {
                    "low": 0,
                    "judgedFlg": false,
                    "medium": 0,
                    "high": 0
                }
            },
            {
                "identityType": 2,
                "idCard": "2102041988",
                "accountId": "2102041988",
                "riskLevel": 3,
                "judgedTime": null,
                "photo": null,
                "hitTime": "2015-12-07 09:44:06",
                "hitNum": 2,
                "featureRuleType": {
                    "low": 0,
                    "judgedFlg": false,
                    "medium": 0,
                    "high": 0
                },
                "hitNmaes": "出入敏感省市,购买制爆组件",
                "judgedFlg": 0,
                "registerType": 2,
                "actionRuleType": {
                    "low": 0,
                    "judgedFlg": false,
                    "medium": 0,
                    "high": 0
                },
                "taobaoName": null,
                "name": "赵某某",
                "relationRuleType": {
                    "low": 0,
                    "judgedFlg": false,
                    "medium": 0,
                    "high": 0
                },
                "accountType": 1,
                "alipayName": null,
                "locusRuleType": {
                    "low": 0,
                    "judgedFlg": false,
                    "medium": 0,
                    "high": 0
                }
            }
        ]
}),
//支付宝基本信息表
hitCollectBO: merge(commonData, {
    "data": {
            "judgedHighTotal": 20,
            "mediumTotal": 15,
            "lowTotal": 60,
            "judgedTotal": 125,
            "hitTotal": 543,
            "highTotal": 50,
            "judgedMediumTotal": 10,
            "judgedLowTotal": 35
        }
})

};
